name: Build and Deploy Readio

on:
  push:
    branches:
      - main       # 每次 push 到 main 分支就触发
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: write     # 允许写权限推送到 gh-pages
  pages: write
  id-token: write

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown jinja2 beautifulsoup4

      - name: Build static site
        run: python build.py

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          # GITHUB_TOKEN 自动提供，无需手动配置
          # 依赖 build job 上传的 artifact
          artifact_name: site
