permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: site  # 输出目录给 deploy job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown jinja2 beautifulsoup4
      - name: Build site
        run: python build.py
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site  # 这里要和 build.py 输出目录一致

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
